include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  "dev-email" {
    defaultVisibilityTimeout = 300
    delay = 0
    receiveMessageWait = 20
    deadLettersQueue {
      name = "dev-email-dlq"
      maxReceiveCount = 3
    }
  }
  "dev-email-dlq" {
  }

  "dev-audit-log" {
    defaultVisibilityTimeout = 300
    delay = 0
    receiveMessageWait = 20
    deadLettersQueue {
      name = "dev-audit-log-dlq"
      maxReceiveCount = 3
    }
  }
  "dev-audit-log-dlq" {
  }
}
